# Generated by Django 4.2.3 on 2023-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_remove_skill_id_alter_skill_skill_name"),
        ("jobs", "0002_alter_jobskills_skill_delete_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(to="skills.skill"),
        ),
        migrations.DeleteModel(
            name="JobSkills",
        ),
    ]
