# Generated by Django 4.2.3 on 2023-10-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_address_job_company_job_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="pub_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 14, 15, 59, 46, 563689, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
