# Generated by Django 4.2.3 on 2023-10-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("RUS", "Russia"),
                            ("KAZ", "Kazakhstan"),
                            ("BEL", "Belarus"),
                        ],
                        max_length=50,
                        verbose_name="country",
                    ),
                ),
                ("region", models.CharField(max_length=50, verbose_name="region")),
                ("city", models.CharField(max_length=50, verbose_name="city")),
                ("street", models.CharField(max_length=50, verbose_name="street")),
                ("building", models.CharField(max_length=6, verbose_name="building")),
                ("room", models.CharField(max_length=5, verbose_name="room")),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="company title"),
                ),
                ("description", models.TextField(verbose_name="company description")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="company email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=12, verbose_name="company phone"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.address",
                        verbose_name="address",
                    ),
                ),
            ],
        ),
    ]
