# Generated by Django 4.2.3 on 2023-10-14 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="USERNAME_FIELD",
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 14, 16, 5, 34, 480007, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
