# Generated by Django 4.2.3 on 2023-10-14 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_username_user_username_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 14, 16, 5, 57, 547071, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
