# Generated by Django 4.2.3 on 2023-10-17 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0003_alter_skill_options_skill_skill_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
        ("users", "0003_alter_user_registration_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentname",
                    models.CharField(max_length=20, verbose_name="user parent name"),
                ),
                ("birthdate", models.DateField()),
                ("phone", models.CharField(max_length=12, verbose_name="user phone")),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.address",
                        verbose_name="user address",
                    ),
                ),
                ("skills", models.ManyToManyField(to="skills.skill")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
