# Generated by Django 4.2.3 on 2023-10-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        ("skills", "0003_alter_skill_options_skill_skill_description_and_more"),
        ("users", "0004_profile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.address",
                verbose_name="user address",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(
                blank=True, null=True, verbose_name="user birthdate"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="parentname",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="user parent name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="user phone"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(blank=True, null=True, to="skills.skill"),
        ),
    ]
