# Generated by Django 4.2.3 on 2023-10-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobskills",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
            ),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
