# Generated by Django 4.2.3 on 2023-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0016_alter_job_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="pub_date",
            field=models.DateField(null=True),
        ),
    ]
