CREATE USER 'diploma'@'localhost' IDENTIFIED BY '2ZJPG@2qE5iGW6';

GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on diploma_web_app.* TO 'diploma'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;